# Stepd build with authenticated relayer (set to latest later)
ARG FIREHOSE_ETHEREUM="35ef8c5"

# Build Bor in a stock Go builder container
FROM golang:1.26-alpine AS builder

RUN apk add --no-cache gcc musl-dev linux-headers git

# Get dependencies - will also be cached if we won't change go.mod/go.sum
COPY go.mod /go-ethereum/
COPY go.sum /go-ethereum/
RUN cd /go-ethereum && go mod download

ADD . /go-ethereum
RUN cd /go-ethereum && go run build/ci.go install -static ./cmd/cli/main.go

FROM   ghcr.io/streamingfast/firehose-ethereum:${FIREHOSE_ETHEREUM}

COPY --from=builder /go-ethereum/build/bin/main.go /usr/local/bin/bor
RUN ln -s /usr/local/bin/bor /app/bor

EXPOSE 8545 8546 30303 30303/udp
