ARG FIREHOSE_ETHEREUM="47bda47"

FROM us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.16.5 as optimism-node

#check https://github.com/Uniswap/unichain-node/docker-compose.yml
FROM us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.13.2 as unichain-node
# Build Geth in a stock Go builder container
FROM golang:1.24.0-alpine as builder

RUN apk add --no-cache gcc musl-dev linux-headers git

# Get dependencies - will also be cached if we won't change go.mod/go.sum
COPY go.mod /go-ethereum/
COPY go.sum /go-ethereum/
RUN cd /go-ethereum && go mod download

ADD . /go-ethereum
RUN cd /go-ethereum && go run build/ci.go install -static ./cmd/geth


# Pull Geth into a second stage deploy alpine container
FROM ghcr.io/streamingfast/firehose-ethereum:${FIREHOSE_ETHEREUM}

#RUN apk add --no-cache ca-certificates

COPY --from=builder /go-ethereum/build/bin/geth /usr/local/bin/
COPY --from=builder /go-ethereum/build/bin/geth /app/geth

COPY --from=optimism-node /usr/local/bin/op-node /app/op-node
COPY --from=unichain-node /usr/local/bin/op-node /app/unichain-node


ENTRYPOINT /app/geth
