ARG FIREHOSE_ETHEREUM="b0c75dd"

# Build Geth in a stock Go builder container
FROM golang:1.24-alpine AS builder

RUN apk add --no-cache make cmake gcc musl-dev linux-headers git bash build-base libc-dev

# Get dependencies - will also be cached if we won't change go.mod/go.sum
COPY go.mod /go-ethereum/
COPY go.sum /go-ethereum/
RUN cd /go-ethereum && go mod download

ADD . /go-ethereum

# For blst
ENV CGO_CFLAGS="-O -D__BLST_PORTABLE__"
ENV CGO_CFLAGS_ALLOW="-O -D__BLST_PORTABLE__"
RUN cd /go-ethereum && go run build/ci.go install -static ./cmd/geth

# Pull Geth into Firehose Core container (geth is statically linked, we can copy it from alpine to ubuntu)
FROM ghcr.io/streamingfast/firehose-ethereum:${FIREHOSE_ETHEREUM}

COPY --from=builder /go-ethereum/build/bin/geth /usr/local/bin/geth
RUN ln -s /usr/local/bin/geth /app/geth

EXPOSE 8545 8546 30303 30303/udp
