// Code generated by gen_dispatch; DO NOT EDIT.

package vm

import (
	"fmt"
	"sync/atomic"

	"github.com/ethereum/go-ethereum/common/math"
	"github.com/ethereum/go-ethereum/params"
	"github.com/holiman/uint256"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ = math.SafeMul
	_ = params.JumpdestGas
	_ uint256.Int
)

// runSwitch is the fast-path EVM interpreter loop using a direct switch
// dispatch for hot opcodes. Inlines hot opcodes directly in the switch body
// (eliminating indirect function calls) and accumulates static gas costs in
// a local variable (eliminating per-opcode heap writes).
//
// This function is only called when no tracer is attached and EIP-4762
// (Verkle) is not active. The existing Run() loop handles those cases.
//
// gasAccum is flushed at control flow points (JUMP, JUMPI, JUMPDEST, STOP,
// INVALID) and the default fallback. Unflushed gasAccum on error is safe:
// non-REVERT errors consume all gas in EVM.Call; REVERT hits the default
// path which flushes first.
//
//nolint:gocognit
func (evm *EVM) runSwitch(
	contract *Contract,
	stack *Stack,
	mem *Memory,
	callContext *ScopeContext,
	jumpTable *JumpTable,
	interrupt *atomic.Bool,
) (ret []byte, err error) {
	code := contract.Code
	codeLen := uint64(len(code))
	var pc uint64
	var gasAccum uint64

	for {
		if interrupt.Load() {
			opcodeCommitInterruptCounter.Inc(1)
			return nil, ErrInterrupt
		}

		var op byte
		if pc < codeLen {
			op = code[pc]
		}

		switch OpCode(op) {
		case STOP:
			if contract.Gas < gasAccum {
				return nil, ErrOutOfGas
			}
			contract.Gas -= gasAccum
			gasAccum = 0
			return nil, errStopToken
		case ADD:
			gasAccum += GasFastestStep
			if stack.top < 2 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 2}
			}
			stack.top--
			y := &stack.data[stack.top-1]
			y.Add(&stack.data[stack.top], y)
		case MUL:
			gasAccum += GasFastStep
			if stack.top < 2 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 2}
			}
			stack.top--
			y := &stack.data[stack.top-1]
			y.Mul(&stack.data[stack.top], y)
		case SUB:
			gasAccum += GasFastestStep
			if stack.top < 2 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 2}
			}
			stack.top--
			y := &stack.data[stack.top-1]
			y.Sub(&stack.data[stack.top], y)
		case DIV:
			gasAccum += GasFastStep
			if stack.top < 2 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 2}
			}
			stack.top--
			y := &stack.data[stack.top-1]
			y.Div(&stack.data[stack.top], y)
		case SDIV:
			gasAccum += GasFastStep
			if stack.top < 2 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 2}
			}
			stack.top--
			y := &stack.data[stack.top-1]
			y.SDiv(&stack.data[stack.top], y)
		case MOD:
			gasAccum += GasFastStep
			if stack.top < 2 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 2}
			}
			stack.top--
			y := &stack.data[stack.top-1]
			y.Mod(&stack.data[stack.top], y)
		case SMOD:
			gasAccum += GasFastStep
			if stack.top < 2 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 2}
			}
			stack.top--
			y := &stack.data[stack.top-1]
			y.SMod(&stack.data[stack.top], y)
		case ADDMOD:
			gasAccum += GasMidStep
			if stack.top < 3 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 3}
			}
			stack.top -= 2
			x := stack.data[stack.top+1]
			y := stack.data[stack.top]
			z := &stack.data[stack.top-1]
			z.AddMod(&x, &y, z)
		case MULMOD:
			gasAccum += GasMidStep
			if stack.top < 3 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 3}
			}
			stack.top -= 2
			x := stack.data[stack.top+1]
			y := stack.data[stack.top]
			z := &stack.data[stack.top-1]
			z.MulMod(&x, &y, z)
		case SIGNEXTEND:
			gasAccum += GasFastStep
			if stack.top < 2 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 2}
			}
			stack.top--
			back := stack.data[stack.top]
			num := &stack.data[stack.top-1]
			num.ExtendSign(num, &back)
		case LT:
			gasAccum += GasFastestStep
			if stack.top < 2 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 2}
			}
			stack.top--
			x := stack.data[stack.top]
			y := &stack.data[stack.top-1]
			if x.Lt(y) {
				y.SetOne()
			} else {
				y.Clear()
			}
		case GT:
			gasAccum += GasFastestStep
			if stack.top < 2 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 2}
			}
			stack.top--
			x := stack.data[stack.top]
			y := &stack.data[stack.top-1]
			if x.Gt(y) {
				y.SetOne()
			} else {
				y.Clear()
			}
		case SLT:
			gasAccum += GasFastestStep
			if stack.top < 2 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 2}
			}
			stack.top--
			x := stack.data[stack.top]
			y := &stack.data[stack.top-1]
			if x.Slt(y) {
				y.SetOne()
			} else {
				y.Clear()
			}
		case SGT:
			gasAccum += GasFastestStep
			if stack.top < 2 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 2}
			}
			stack.top--
			x := stack.data[stack.top]
			y := &stack.data[stack.top-1]
			if x.Sgt(y) {
				y.SetOne()
			} else {
				y.Clear()
			}
		case EQ:
			gasAccum += GasFastestStep
			if stack.top < 2 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 2}
			}
			stack.top--
			x := stack.data[stack.top]
			y := &stack.data[stack.top-1]
			if x.Eq(y) {
				y.SetOne()
			} else {
				y.Clear()
			}
		case ISZERO:
			gasAccum += GasFastestStep
			if stack.top < 1 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 1}
			}
			x := &stack.data[stack.top-1]
			if x.IsZero() {
				x.SetOne()
			} else {
				x.Clear()
			}
		case AND:
			gasAccum += GasFastestStep
			if stack.top < 2 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 2}
			}
			stack.top--
			y := &stack.data[stack.top-1]
			y.And(&stack.data[stack.top], y)
		case OR:
			gasAccum += GasFastestStep
			if stack.top < 2 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 2}
			}
			stack.top--
			y := &stack.data[stack.top-1]
			y.Or(&stack.data[stack.top], y)
		case XOR:
			gasAccum += GasFastestStep
			if stack.top < 2 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 2}
			}
			stack.top--
			y := &stack.data[stack.top-1]
			y.Xor(&stack.data[stack.top], y)
		case NOT:
			gasAccum += GasFastestStep
			if stack.top < 1 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 1}
			}
			x := &stack.data[stack.top-1]
			x.Not(x)
		case BYTE:
			gasAccum += GasFastestStep
			if stack.top < 2 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 2}
			}
			stack.top--
			th := stack.data[stack.top]
			val := &stack.data[stack.top-1]
			val.Byte(&th)
		case SHL:
			gasAccum += GasFastestStep
			if stack.top < 2 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 2}
			}
			stack.top--
			shift := stack.data[stack.top]
			value := &stack.data[stack.top-1]
			if shift.LtUint64(256) {
				value.Lsh(value, uint(shift.Uint64()))
			} else {
				value.Clear()
			}
		case SHR:
			gasAccum += GasFastestStep
			if stack.top < 2 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 2}
			}
			stack.top--
			shift := stack.data[stack.top]
			value := &stack.data[stack.top-1]
			if shift.LtUint64(256) {
				value.Rsh(value, uint(shift.Uint64()))
			} else {
				value.Clear()
			}
		case SAR:
			gasAccum += GasFastestStep
			if stack.top < 2 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 2}
			}
			stack.top--
			shift := stack.data[stack.top]
			value := &stack.data[stack.top-1]
			if shift.GtUint64(256) {
				if value.Sign() >= 0 {
					value.Clear()
				} else {
					value.SetAllOne()
				}
			} else {
				value.SRsh(value, uint(shift.Uint64()))
			}
		case POP:
			gasAccum += GasQuickStep
			if stack.top < 1 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 1}
			}
			stack.top--
		case JUMP:
			gasAccum += GasMidStep
			if contract.Gas < gasAccum {
				return nil, ErrOutOfGas
			}
			contract.Gas -= gasAccum
			gasAccum = 0
			if stack.top < 1 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 1}
			}
			stack.top--
			pos := stack.data[stack.top]
			if evm.abort.Load() {
				return nil, errStopToken
			}
			if !contract.validJumpdest(&pos) {
				return nil, ErrInvalidJump
			}
			pc = pos.Uint64()
			continue
		case JUMPI:
			gasAccum += GasSlowStep
			if contract.Gas < gasAccum {
				return nil, ErrOutOfGas
			}
			contract.Gas -= gasAccum
			gasAccum = 0
			if stack.top < 2 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 2}
			}
			stack.top -= 2
			pos := stack.data[stack.top+1]
			cond := stack.data[stack.top]
			if evm.abort.Load() {
				return nil, errStopToken
			}
			if !cond.IsZero() {
				if !contract.validJumpdest(&pos) {
					return nil, ErrInvalidJump
				}
				pc = pos.Uint64()
				continue
			}
		case PC:
			gasAccum += GasQuickStep
			if stack.top >= int(params.StackLimit) {
				return nil, &ErrStackOverflow{stackLen: stack.top, limit: int(params.StackLimit) - 1}
			}
			stack.data[stack.top].SetUint64(pc)
			stack.top++
		case MSIZE:
			gasAccum += GasQuickStep
			if stack.top >= int(params.StackLimit) {
				return nil, &ErrStackOverflow{stackLen: stack.top, limit: int(params.StackLimit) - 1}
			}
			stack.data[stack.top].SetUint64(uint64(mem.Len()))
			stack.top++
		case JUMPDEST:
			gasAccum += params.JumpdestGas
			if contract.Gas < gasAccum {
				return nil, ErrOutOfGas
			}
			contract.Gas -= gasAccum
			gasAccum = 0
		case INVALID:
			if contract.Gas < gasAccum {
				return nil, ErrOutOfGas
			}
			contract.Gas -= gasAccum
			gasAccum = 0
			return nil, &ErrInvalidOpCode{opcode: INVALID}
		case PUSH0:
			gasAccum += GasQuickStep
			if stack.top >= int(params.StackLimit) {
				return nil, &ErrStackOverflow{stackLen: stack.top, limit: int(params.StackLimit) - 1}
			}
			stack.data[stack.top].Clear()
			stack.top++
		case PUSH1:
			gasAccum += GasFastestStep
			if stack.top >= int(params.StackLimit) {
				return nil, &ErrStackOverflow{stackLen: stack.top, limit: int(params.StackLimit) - 1}
			}
			pc++
			if pc < codeLen {
				stack.data[stack.top].SetUint64(uint64(code[pc]))
			} else {
				stack.data[stack.top].Clear()
			}
			stack.top++
		case PUSH2:
			gasAccum += GasFastestStep
			if stack.top >= int(params.StackLimit) {
				return nil, &ErrStackOverflow{stackLen: stack.top, limit: int(params.StackLimit) - 1}
			}
			if pc+2 < codeLen {
				stack.data[stack.top].SetBytes2(code[pc+1 : pc+3])
			} else if pc+1 < codeLen {
				stack.data[stack.top].SetUint64(uint64(code[pc+1]) << 8)
			} else {
				stack.data[stack.top].Clear()
			}
			pc += 2
			stack.top++
		case PUSH3:
			gasAccum += GasFastestStep
			if stack.top >= int(params.StackLimit) {
				return nil, &ErrStackOverflow{stackLen: stack.top, limit: int(params.StackLimit) - 1}
			}
			start := min(codeLen, pc+1)
			end := min(codeLen, pc+4)
			stack.data[stack.top].SetBytes(code[start:end])
			if missing := 3 - int(end-start); missing > 0 {
				stack.data[stack.top].Lsh(&stack.data[stack.top], uint(8*missing))
			}
			pc += 3
			stack.top++
		case PUSH4:
			gasAccum += GasFastestStep
			if stack.top >= int(params.StackLimit) {
				return nil, &ErrStackOverflow{stackLen: stack.top, limit: int(params.StackLimit) - 1}
			}
			start := min(codeLen, pc+1)
			end := min(codeLen, pc+5)
			stack.data[stack.top].SetBytes(code[start:end])
			if missing := 4 - int(end-start); missing > 0 {
				stack.data[stack.top].Lsh(&stack.data[stack.top], uint(8*missing))
			}
			pc += 4
			stack.top++
		case PUSH5, PUSH6, PUSH7, PUSH8, PUSH9, PUSH10, PUSH11, PUSH12, PUSH13, PUSH14, PUSH15, PUSH16, PUSH17, PUSH18, PUSH19, PUSH20, PUSH21, PUSH22, PUSH23, PUSH24, PUSH25, PUSH26, PUSH27, PUSH28, PUSH29, PUSH30, PUSH31, PUSH32:
			gasAccum += GasFastestStep
			if stack.top >= int(params.StackLimit) {
				return nil, &ErrStackOverflow{stackLen: stack.top, limit: int(params.StackLimit) - 1}
			}
			n := uint64(op - byte(PUSH0))
			start := min(codeLen, pc+1)
			end := min(codeLen, pc+1+n)
			stack.data[stack.top].SetBytes(code[start:end])
			if missing := int(n) - int(end-start); missing > 0 {
				stack.data[stack.top].Lsh(&stack.data[stack.top], uint(8*missing))
			}
			pc += n
			stack.top++
		case DUP1:
			gasAccum += GasFastestStep
			if stack.top < 1 || stack.top >= int(params.StackLimit) {
				if stack.top < 1 {
					return nil, &ErrStackUnderflow{stackLen: stack.top, required: 1}
				}
				return nil, &ErrStackOverflow{stackLen: stack.top, limit: int(params.StackLimit) - 1}
			}
			stack.data[stack.top] = stack.data[stack.top-1]
			stack.top++
		case DUP2:
			gasAccum += GasFastestStep
			if stack.top < 2 || stack.top >= int(params.StackLimit) {
				if stack.top < 2 {
					return nil, &ErrStackUnderflow{stackLen: stack.top, required: 2}
				}
				return nil, &ErrStackOverflow{stackLen: stack.top, limit: int(params.StackLimit) - 1}
			}
			stack.data[stack.top] = stack.data[stack.top-2]
			stack.top++
		case DUP3:
			gasAccum += GasFastestStep
			if stack.top < 3 || stack.top >= int(params.StackLimit) {
				if stack.top < 3 {
					return nil, &ErrStackUnderflow{stackLen: stack.top, required: 3}
				}
				return nil, &ErrStackOverflow{stackLen: stack.top, limit: int(params.StackLimit) - 1}
			}
			stack.data[stack.top] = stack.data[stack.top-3]
			stack.top++
		case DUP4:
			gasAccum += GasFastestStep
			if stack.top < 4 || stack.top >= int(params.StackLimit) {
				if stack.top < 4 {
					return nil, &ErrStackUnderflow{stackLen: stack.top, required: 4}
				}
				return nil, &ErrStackOverflow{stackLen: stack.top, limit: int(params.StackLimit) - 1}
			}
			stack.data[stack.top] = stack.data[stack.top-4]
			stack.top++
		case DUP5:
			gasAccum += GasFastestStep
			if stack.top < 5 || stack.top >= int(params.StackLimit) {
				if stack.top < 5 {
					return nil, &ErrStackUnderflow{stackLen: stack.top, required: 5}
				}
				return nil, &ErrStackOverflow{stackLen: stack.top, limit: int(params.StackLimit) - 1}
			}
			stack.data[stack.top] = stack.data[stack.top-5]
			stack.top++
		case DUP6:
			gasAccum += GasFastestStep
			if stack.top < 6 || stack.top >= int(params.StackLimit) {
				if stack.top < 6 {
					return nil, &ErrStackUnderflow{stackLen: stack.top, required: 6}
				}
				return nil, &ErrStackOverflow{stackLen: stack.top, limit: int(params.StackLimit) - 1}
			}
			stack.data[stack.top] = stack.data[stack.top-6]
			stack.top++
		case DUP7:
			gasAccum += GasFastestStep
			if stack.top < 7 || stack.top >= int(params.StackLimit) {
				if stack.top < 7 {
					return nil, &ErrStackUnderflow{stackLen: stack.top, required: 7}
				}
				return nil, &ErrStackOverflow{stackLen: stack.top, limit: int(params.StackLimit) - 1}
			}
			stack.data[stack.top] = stack.data[stack.top-7]
			stack.top++
		case DUP8:
			gasAccum += GasFastestStep
			if stack.top < 8 || stack.top >= int(params.StackLimit) {
				if stack.top < 8 {
					return nil, &ErrStackUnderflow{stackLen: stack.top, required: 8}
				}
				return nil, &ErrStackOverflow{stackLen: stack.top, limit: int(params.StackLimit) - 1}
			}
			stack.data[stack.top] = stack.data[stack.top-8]
			stack.top++
		case DUP9:
			gasAccum += GasFastestStep
			if stack.top < 9 || stack.top >= int(params.StackLimit) {
				if stack.top < 9 {
					return nil, &ErrStackUnderflow{stackLen: stack.top, required: 9}
				}
				return nil, &ErrStackOverflow{stackLen: stack.top, limit: int(params.StackLimit) - 1}
			}
			stack.data[stack.top] = stack.data[stack.top-9]
			stack.top++
		case DUP10:
			gasAccum += GasFastestStep
			if stack.top < 10 || stack.top >= int(params.StackLimit) {
				if stack.top < 10 {
					return nil, &ErrStackUnderflow{stackLen: stack.top, required: 10}
				}
				return nil, &ErrStackOverflow{stackLen: stack.top, limit: int(params.StackLimit) - 1}
			}
			stack.data[stack.top] = stack.data[stack.top-10]
			stack.top++
		case DUP11:
			gasAccum += GasFastestStep
			if stack.top < 11 || stack.top >= int(params.StackLimit) {
				if stack.top < 11 {
					return nil, &ErrStackUnderflow{stackLen: stack.top, required: 11}
				}
				return nil, &ErrStackOverflow{stackLen: stack.top, limit: int(params.StackLimit) - 1}
			}
			stack.data[stack.top] = stack.data[stack.top-11]
			stack.top++
		case DUP12:
			gasAccum += GasFastestStep
			if stack.top < 12 || stack.top >= int(params.StackLimit) {
				if stack.top < 12 {
					return nil, &ErrStackUnderflow{stackLen: stack.top, required: 12}
				}
				return nil, &ErrStackOverflow{stackLen: stack.top, limit: int(params.StackLimit) - 1}
			}
			stack.data[stack.top] = stack.data[stack.top-12]
			stack.top++
		case DUP13:
			gasAccum += GasFastestStep
			if stack.top < 13 || stack.top >= int(params.StackLimit) {
				if stack.top < 13 {
					return nil, &ErrStackUnderflow{stackLen: stack.top, required: 13}
				}
				return nil, &ErrStackOverflow{stackLen: stack.top, limit: int(params.StackLimit) - 1}
			}
			stack.data[stack.top] = stack.data[stack.top-13]
			stack.top++
		case DUP14:
			gasAccum += GasFastestStep
			if stack.top < 14 || stack.top >= int(params.StackLimit) {
				if stack.top < 14 {
					return nil, &ErrStackUnderflow{stackLen: stack.top, required: 14}
				}
				return nil, &ErrStackOverflow{stackLen: stack.top, limit: int(params.StackLimit) - 1}
			}
			stack.data[stack.top] = stack.data[stack.top-14]
			stack.top++
		case DUP15:
			gasAccum += GasFastestStep
			if stack.top < 15 || stack.top >= int(params.StackLimit) {
				if stack.top < 15 {
					return nil, &ErrStackUnderflow{stackLen: stack.top, required: 15}
				}
				return nil, &ErrStackOverflow{stackLen: stack.top, limit: int(params.StackLimit) - 1}
			}
			stack.data[stack.top] = stack.data[stack.top-15]
			stack.top++
		case DUP16:
			gasAccum += GasFastestStep
			if stack.top < 16 || stack.top >= int(params.StackLimit) {
				if stack.top < 16 {
					return nil, &ErrStackUnderflow{stackLen: stack.top, required: 16}
				}
				return nil, &ErrStackOverflow{stackLen: stack.top, limit: int(params.StackLimit) - 1}
			}
			stack.data[stack.top] = stack.data[stack.top-16]
			stack.top++
		case SWAP1:
			gasAccum += GasFastestStep
			t := stack.top - 1
			if t < 1 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 2}
			}
			stack.data[t], stack.data[t-1] = stack.data[t-1], stack.data[t]
		case SWAP2:
			gasAccum += GasFastestStep
			t := stack.top - 1
			if t < 2 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 3}
			}
			stack.data[t], stack.data[t-2] = stack.data[t-2], stack.data[t]
		case SWAP3:
			gasAccum += GasFastestStep
			t := stack.top - 1
			if t < 3 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 4}
			}
			stack.data[t], stack.data[t-3] = stack.data[t-3], stack.data[t]
		case SWAP4:
			gasAccum += GasFastestStep
			t := stack.top - 1
			if t < 4 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 5}
			}
			stack.data[t], stack.data[t-4] = stack.data[t-4], stack.data[t]
		case SWAP5:
			gasAccum += GasFastestStep
			t := stack.top - 1
			if t < 5 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 6}
			}
			stack.data[t], stack.data[t-5] = stack.data[t-5], stack.data[t]
		case SWAP6:
			gasAccum += GasFastestStep
			t := stack.top - 1
			if t < 6 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 7}
			}
			stack.data[t], stack.data[t-6] = stack.data[t-6], stack.data[t]
		case SWAP7:
			gasAccum += GasFastestStep
			t := stack.top - 1
			if t < 7 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 8}
			}
			stack.data[t], stack.data[t-7] = stack.data[t-7], stack.data[t]
		case SWAP8:
			gasAccum += GasFastestStep
			t := stack.top - 1
			if t < 8 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 9}
			}
			stack.data[t], stack.data[t-8] = stack.data[t-8], stack.data[t]
		case SWAP9:
			gasAccum += GasFastestStep
			t := stack.top - 1
			if t < 9 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 10}
			}
			stack.data[t], stack.data[t-9] = stack.data[t-9], stack.data[t]
		case SWAP10:
			gasAccum += GasFastestStep
			t := stack.top - 1
			if t < 10 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 11}
			}
			stack.data[t], stack.data[t-10] = stack.data[t-10], stack.data[t]
		case SWAP11:
			gasAccum += GasFastestStep
			t := stack.top - 1
			if t < 11 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 12}
			}
			stack.data[t], stack.data[t-11] = stack.data[t-11], stack.data[t]
		case SWAP12:
			gasAccum += GasFastestStep
			t := stack.top - 1
			if t < 12 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 13}
			}
			stack.data[t], stack.data[t-12] = stack.data[t-12], stack.data[t]
		case SWAP13:
			gasAccum += GasFastestStep
			t := stack.top - 1
			if t < 13 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 14}
			}
			stack.data[t], stack.data[t-13] = stack.data[t-13], stack.data[t]
		case SWAP14:
			gasAccum += GasFastestStep
			t := stack.top - 1
			if t < 14 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 15}
			}
			stack.data[t], stack.data[t-14] = stack.data[t-14], stack.data[t]
		case SWAP15:
			gasAccum += GasFastestStep
			t := stack.top - 1
			if t < 15 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 16}
			}
			stack.data[t], stack.data[t-15] = stack.data[t-15], stack.data[t]
		case SWAP16:
			gasAccum += GasFastestStep
			t := stack.top - 1
			if t < 16 {
				return nil, &ErrStackUnderflow{stackLen: stack.top, required: 17}
			}
			stack.data[t], stack.data[t-16] = stack.data[t-16], stack.data[t]
		default:
			if contract.Gas < gasAccum {
				return nil, ErrOutOfGas
			}
			contract.Gas -= gasAccum
			gasAccum = 0

			operation := jumpTable[OpCode(op)]
			if operation == nil || operation.undefined {
				return nil, &ErrInvalidOpCode{opcode: OpCode(op)}
			}

			if sLen := stack.len(); sLen < operation.minStack {
				return nil, &ErrStackUnderflow{stackLen: sLen, required: operation.minStack}
			} else if sLen > operation.maxStack {
				return nil, &ErrStackOverflow{stackLen: sLen, limit: operation.maxStack}
			}

			cost := operation.constantGas
			if contract.Gas < cost {
				return nil, ErrOutOfGas
			}
			contract.Gas -= cost

			if operation.dynamicGas != nil {
				var memorySize uint64
				if operation.memorySize != nil {
					memSize, overflow := operation.memorySize(stack)
					if overflow {
						return nil, ErrGasUintOverflow
					}
					var ovf bool
					if memorySize, ovf = math.SafeMul(toWordSize(memSize), 32); ovf {
						return nil, ErrGasUintOverflow
					}
				}
				var dynamicCost uint64
				dynamicCost, err = operation.dynamicGas(evm, contract, stack, mem, memorySize)
				if err != nil {
					return nil, fmt.Errorf("%w: %v", ErrOutOfGas, err)
				}
				if contract.Gas < dynamicCost {
					return nil, ErrOutOfGas
				}
				contract.Gas -= dynamicCost
				if memorySize > 0 {
					mem.Resize(memorySize)
				}
			}

			ret, err = operation.execute(&pc, evm, callContext)
			if err != nil {
				if err == errStopToken {
					return ret, errStopToken
				}
				return ret, err
			}
		}
		pc++
	}
}
